repos:
  - repo: local
    hooks:
      - id: poetry2setup
        name: Generate setup.py from poetry
        entry: bash -c 'poetry2setup > setup.py'
        language: python
        additional_dependencies:
          - poetry2setup
        files: ^pyproject\.toml$


  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: ^setup\.py$
