[tool.poetry]
name = "mindframe"
version = "0.1.15"
description = "A Python package for the `mindframe` project"
authors = [
    "Ben Whalley <ben.whalley@plymouth.ac.uk>",
    "Ali Bidaran <ali@example.com>"
]

[tool.poetry.dependencies]
python = ">=3.11, <4.0"
Django = "^5.0.6"
pydantic = "^2.9.2"
pandoc = "^2.4"
psycopg2 = {markers = "sys_platform == 'linux'", version = "~=2.9"}
psycopg2_binary = {markers = "sys_platform == 'darwin'", version = "~=2.9"}
celery = "^5.4.0"
redis = "^5.2"
gradio = "^5.5.0"
shortuuid = "^1.0.13"
pgvector = "*"
sentence-transformers = "^3.3.0"
dj-database-url = "^2.1.0"
django-shortuuidfield = "^0.1.3"
django-autoslug = "^1.9.9"
boto3 = "^1.34.119"
rules = "^3.4"
honcho = "^1.1.0"
gunicorn = "^22.0.0"
uvicorn = "^0.30.1"
python-dotenv = "^1.0.1"
black = "^24.4.2"
django-environ = "^0.11.2"
poetry-plugin-export = "^1.8.0"
django-lifecycle = "^1.2.4"
gevent = "^24.11"
ruamel-yaml = "^0.18.6"
instructor = "^1.6.4"
python-box = "^7.2.0"
haystack-ai = "^2.7.0"
pgvector-haystack = "^1.2.0"
haystack-experimental="0.3.0"
ollama-haystack = "^2.0.0"

[tool.poetry.scripts]
mindframe-bot = "mindframe.chatbot:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
force_single_line = true
