# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="mindframe",
    version="0.1.6",
    description="A Python package for the `mindframe` project",
    python_requires="<4.0,>=3.11",
    author="Ben Whalley",
    author_email="ben.whalley@plymouth.ac.uk",
    maintainer="Ali Bidaran",
    maintainer_email="ali@example.com",
    entry_points={"console_scripts": ["mindframe-bot = mindframe.chatbot:main"]},
    packages=["mindframe", "mindframe.migrations", "mindframe.tests"],
    package_dir={"": "."},
    package_data={"mindframe": ["static/mindframe/css/*.css", "static/mindframe/js/*.js"]},
    install_requires=[
        "black==24.*,>=24.4.2",
        "boto3==1.*,>=1.34.119",
        "celery==5.*,>=5.4.0",
        "dephell==0.*,>=0.8.3",
        "dj-database-url==2.*,>=2.1.0",
        "django==5.*,>=5.0.6",
        "django-autoslug==1.*,>=1.9.9",
        "django-environ==0.*,>=0.11.2",
        "django-shortuuidfield==0.*,>=0.1.3",
        "gradio==5.*,>=5.5.0",
        "gunicorn==22.*,>=22.0.0",
        "honcho==1.*,>=1.1.0",
        "litellm==1.*,>=1.51.0",
        "magentic==0.*,>=0.32.0",
        "pandoc==2.*,>=2.4.0",
        "pgvector==0.*,>=0.3.6",
        "poetry-plugin-export==1.*,>=1.8.0",
        "psycopg2==2.*,>=2.9.9",
        "pydantic==2.*,>=2.9.2",
        "python-dotenv==1.*,>=1.0.1",
        "rules==3.*,>=3.4.0",
        "sentence-transformers==3.*,>=3.3.0",
        "setuptools==58.0.4",
        "shortuuid==1.*,>=1.0.13",
        "uvicorn==0.*,>=0.30.1",
    ],
)
