# Generated by Django 5.1.2 on 2024-11-07 14:02

import mindframe.return_type_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0002_treatmentsessionstate_delete_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgementreturntype",
            name="schema",
        ),
        migrations.AddField(
            model_name="judgementreturntype",
            name="pydantic_model",
            field=models.CharField(
                choices=[
                    (
                        "CommentedBooleanResponse",
                        None,
                    ),
                    ("ComplexNote", None),
                    ("BriefNote", None),
                ],
                default="BriefNote",
                max_length=255,
            ),
        ),
    ]
