# Generated by Django 5.1.2 on 2024-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0003_remove_judgementreturntype_schema_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgementreturntype",
            name="pydantic_model",
        ),
        migrations.AddField(
            model_name="judgementreturntype",
            name="pydantic_model_name",
            field=models.CharField(
                choices=[
                    ("CommentedBooleanResponse", "CommentedBooleanResponse"),
                    ("ComplexNote", "ComplexNote"),
                    ("BriefNote", "BriefNote"),
                ],
                default="BriefNote",
                max_length=255,
            ),
        ),
    ]
