# Generated by Django 5.1.3 on 2024-11-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0004_remove_judgementreturntype_pydantic_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="response_format_instructions",
            field=models.TextField(
                default="- respond in a single sentence\n",
                help_text="Instructions for the bot on how to format it's response. Best done as a markdown list. Can be included as {{intervention.response_format_instructions}} in the prompt template.",
            ),
        ),
    ]
