# Generated by Django 5.1.5 on 2025-02-10 01:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0004_alter_note_uuid_alter_turn_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervention",
            name="short_title",
        ),
        migrations.AlterField(
            model_name="intervention",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True),
        ),
    ]
