# Generated by Django 5.1.3 on 2024-11-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0005_intervention_response_format_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="session_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mindframe.treatmentsessionstate",
            ),
        ),
    ]
