# Generated by Django 5.1.5 on 2025-02-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0005_remove_intervention_short_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
