# Generated by Django 5.1.3 on 2024-11-08 14:38

import shortuuid
from django.db import migrations, models


def generate_short_uuid():
    return shortuuid.uuid().lower()


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0007_remove_turn_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentsession",
            name="uuid",
            field=models.CharField(
                default=generate_short_uuid,
                editable=False,
                null=True,
                unique=False,
            ),
        ),
    ]
