# Generated by Django 5.1.5 on 2025-02-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0007_transition_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transition",
            options={"ordering": ["priority"]},
        ),
    ]
