# Generated by Django 5.1.5 on 2025-02-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0008_alter_transition_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_synthetic",
            field=models.BooleanField(default=False),
        ),
    ]
