# Generated by Django 5.1.5 on 2025-02-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0009_conversation_is_synthetic"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="opening_line",
            field=models.TextField(
                blank=True,
                help_text="Opening statements if no conversation history exists. E.g. 'How are you today?'",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="text_source",
            field=models.CharField(
                choices=[("human", "Human"), ("AI", "AI"), ("opening", "Opening")],
                default="human",
                max_length=25,
            ),
        ),
    ]
