# Generated by Django 5.1.3 on 2024-11-08 14:45

from django.db import migrations, models
import shortuuid


def generate_short_uuid():
    return shortuuid.uuid().lower()


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0009_auto_20241108_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmentsession",
            name="uuid",
            field=models.CharField(
                default=generate_short_uuid,
                editable=False,
                unique=True,
            ),
        ),
    ]
