# Generated by Django 5.1.3 on 2024-11-11 08:10

from django.db import migrations


def populate_conditions_text(apps, schema_editor):
    Transition = apps.get_model("mindframe", "Transition")
    for transition in Transition.objects.all():
        transition.conditions_text = "\n".join(transition.conditions)
        transition.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0011_remove_transition_judgements_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_conditions_text),
    ]
