# Generated by Django 5.1.5 on 2025-02-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0011_offlinestepjudgement_step_offline_judgements"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="judgement",
            unique_together={("intervention", "variable_name")},
        ),
        migrations.RemoveField(
            model_name="judgement",
            name="title",
        ),
    ]
