# Generated by Django 5.1.3 on 2024-11-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0012_auto_20241111_0810"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transition",
            name="conditions",
        ),
    ]
