# Generated by Django 5.1.5 on 2025-02-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0013_remove_step_offline_judgements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="telegram_conversation_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="default_fake_client",
            field=models.ForeignKey(
                blank=True,
                help_text="Default intervention to choose as a partner when creating a new Synthetic conversation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mindframe.intervention",
            ),
        ),
    ]
