# Generated by Django 5.1.3 on 2024-11-11 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0014_rename_conditions_text_transition_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="step",
            name="judgements",
        ),
        migrations.AddField(
            model_name="stepjudgement",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stepjudgement",
            name="step",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stepjudgements",
                to="mindframe.step",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stepjudgement",
            name="judgement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stepjudgements",
                to="mindframe.stepjudgement",
            ),
        ),
    ]
