# Generated by Django 5.1.5 on 2025-02-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0014_conversation_telegram_conversation_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="telegram_conversation_user",
            new_name="telegram_conversation_id",
        ),
    ]
