# Generated by Django 5.1.3 on 2024-11-11 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0015_remove_step_judgements_stepjudgement_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="judgements",
            field=models.ManyToManyField(
                through="mindframe.StepJudgement", to="mindframe.judgement"
            ),
        ),
        migrations.AlterField(
            model_name="stepjudgement",
            name="judgement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stepjudgements",
                to="mindframe.judgement",
            ),
        ),
    ]
