# Generated by Django 5.1.5 on 2025-02-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0016_conversation_archived"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("archived", "telegram_conversation_id")},
        ),
    ]
