# Generated by Django 5.1.5 on 2025-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0017_alter_conversation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="is_default_intervention",
            field=models.BooleanField(default=False),
        ),
    ]
