# Generated by Django 5.1.3 on 2024-11-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0017_alter_stepjudgement_options_stepjudgement_once_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgement",
            name="return_type",
        ),
        migrations.AddField(
            model_name="judgement",
            name="pydantic_model_name",
            field=models.CharField(
                choices=[
                    ("CommentedBooleanResponse", "CommentedBooleanResponse"),
                    ("ComplexNote", "ComplexNote"),
                    ("BriefNote", "BriefNote"),
                    ("OptionalText", "OptionalText"),
                    ("ForcedChoice", "ForcedChoice"),
                ],
                default="BriefNote",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="JudgementReturnType",
        ),
    ]
