# Generated by Django 5.1.3 on 2024-11-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0018_remove_judgement_return_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgement",
            name="valid_options",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
