# Generated by Django 5.1.5 on 2025-02-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0018_intervention_is_default_intervention"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together=set(),
        ),
    ]
