# Generated by Django 5.1.3 on 2024-11-11 12:05

import mindframe.models
from django.db import migrations, models

import shortuuid


def generate_short_uuid():
    return shortuuid.uuid().lower()


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0019_judgement_valid_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="uuid",
            field=models.CharField(
                default=generate_short_uuid,
                editable=False,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turn",
            name="uuid",
            field=models.CharField(
                default=generate_short_uuid,
                editable=False,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="example",
            unique_together={("intervention", "title")},
        ),
    ]
