# Generated by Django 5.1.3 on 2024-11-11 13:19

import mindframe.models
from django.db import migrations, models

import shortuuid


def generate_short_uuid():
    return shortuuid.uuid().lower()


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0021_auto_20241111_1206"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stepjudgement",
            options={},
        ),
        migrations.RemoveField(
            model_name="stepjudgement",
            name="order",
        ),
        migrations.AlterField(
            model_name="note",
            name="uuid",
            field=models.CharField(
                default=generate_short_uuid,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="uuid",
            field=models.CharField(
                default=generate_short_uuid,
                editable=False,
                unique=True,
            ),
        ),
    ]
