# Generated by Django 5.1.5 on 2025-02-13 09:51

import mindframe.shortuuidfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0021_auto_20250213_0904"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="inputs",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="uuid",
            field=mindframe.shortuuidfield.MFShortUUIDField(
                blank=True, editable=False, max_length=27
            ),
        ),
    ]
