# Generated by Django 5.1.5 on 2025-02-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0022_remove_note_inputs_alter_conversation_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="intervention_type",
            field=models.CharField(
                choices=[
                    ("therapy", "A therapeutic intervention"),
                    ("client", "A simulated client"),
                ],
                default="therapy",
                max_length=30,
            ),
        ),
    ]
