# Generated by Django 5.1.3 on 2024-11-11 14:31

import mindframe.models
from django.db import migrations, models


import shortuuid


def generate_short_uuid():
    return shortuuid.uuid().lower()



class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0022_alter_stepjudgement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="uuid",
            field=models.CharField(
                default=generate_short_uuid,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="uuid",
            field=models.CharField(
                default=generate_short_uuid,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="uuid",
            field=models.CharField(
                default=generate_short_uuid,
                editable=False,
                unique=True,
            ),
        ),
    ]
