# Generated by Django 5.1.5 on 2025-02-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0025_remove_conversation_default_fake_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="synthetic_turns_scheduled",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
