# Generated by Django 5.1.3 on 2024-11-12 09:04

import mindframe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0025_note_session_state_alter_note_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="session",
        ),
    ]
