# Generated by Django 5.1.3 on 2024-11-12 12:21

import django.db.models.deletion
import django.utils.timezone
import mindframe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0026_remove_note_session_alter_note_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("traceback", models.TextField()),
                (
                    "session_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mindframe.treatmentsessionstate",
                    ),
                ),
            ],
        ),
    ]
