# Generated by Django 5.1.5 on 2025-02-20 16:23

import autoslug.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0026_conversation_synthetic_turns_scheduled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterField(
            model_name="intervention",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=True, populate_from="title", unique=True),
        ),
        migrations.AlterField(
            model_name="memorychunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AlterField(
            model_name="turn",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AlterField(
            model_name="turn",
            name="text_source",
            field=models.CharField(
                choices=[
                    ("human", "Human"),
                    ("generated", "AI generated"),
                    ("opening", "Opening"),
                ],
                default="human",
                max_length=25,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customuser",
            unique_together={("username",)},
        ),
        migrations.AlterUniqueTogether(
            name="llm",
            unique_together={("model_name",)},
        ),
    ]
