# Generated by Django 5.1.6 on 2025-02-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0027_alter_customuser_options_alter_intervention_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["timestamp"]},
        ),
    ]
