# Generated by Django 5.1.6 on 2025-03-07 20:03

import django.db.models.deletion
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0029_intervention_default_speaker_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        default="every week on Friday at 8pm",
                        help_text="A natural language string (in English) defining the pattern of repeats, following the last client-initiated turn. E.g. 'every 30 minutes', 'every tue and thur at 1pm' or 'every weekday at 9am'.",
                        max_length=1024,
                    ),
                ),
                (
                    "for_a_period_of",
                    models.CharField(
                        default="3 weeks",
                        help_text="Natural language string defining how long the repeating rule should apply for. Based on the LAST client-initiated turn. E.g. '4 hours', '3 weeks' or '1 year'",
                        max_length=1024,
                    ),
                ),
                (
                    "not_within_n_hours",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="If set, the nudge will not be scheduled within this many hours of the last client-initiated turn in the conversation.",
                    ),
                ),
                (
                    "intervention",
                    models.ManyToManyField(related_name="nudges", to="mindframe.intervention"),
                ),
                (
                    "nudge_during",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which Steps should this Nudge be applied to. If blank, applies to all Steps",
                        related_name="nudges",
                        to="mindframe.step",
                    ),
                ),
                (
                    "step_to_use",
                    models.ForeignKey(
                        help_text="Which Step to use as a script for the Nudge",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_by_nudges",
                        to="mindframe.step",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="turn",
            name="nudge",
            field=models.ForeignKey(
                blank=True,
                help_text="The scheduled Nudge which generated this turn (if any)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mindframe.nudge",
            ),
        ),
    ]
