# Generated by Django 5.1.3 on 2024-11-12 16:12

import pgvector.django.vector
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0029_example_embedding_alter_note_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
