# Generated by Django 5.1.6 on 2025-03-10 10:58

import django.db.models.deletion
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0030_nudge_turn_nudge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nudge",
            name="not_within_n_hours",
        ),
        migrations.AddField(
            model_name="nudge",
            name="not_within_n_minutes",
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text="If set, the nudge will not be scheduled within this many hours of the last client-initiated turn in the conversation.",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledNudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("due", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "completed_turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_nudges",
                        to="mindframe.turn",
                    ),
                ),
                (
                    "nudge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_nudges",
                        to="mindframe.nudge",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nudges",
                        to="mindframe.turn",
                    ),
                ),
            ],
            options={
                "ordering": ["due"],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
