# Generated by Django 5.1.6 on 2025-03-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0031_remove_nudge_not_within_n_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="synthetic_therapist",
            field=models.ForeignKey(
                blank=True,
                help_text="Default intervention to choose as a therapist when creating a new Synthetic conversation turns",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synthetic_therapist_conversations",
                to="mindframe.intervention",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="synthetic_client",
            field=models.ForeignKey(
                blank=True,
                help_text="Default intervention to choose as a client when creating a new Synthetic conversation turns",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synthetic_client_conversations",
                to="mindframe.intervention",
            ),
        ),
        migrations.AlterField(
            model_name="nudge",
            name="nudge_during",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which Steps should this Nudge be applied to. If blank, applies to all Steps",
                related_name="nudges_which_can_apply",
                to="mindframe.step",
            ),
        ),
        migrations.AlterField(
            model_name="nudge",
            name="step_to_use",
            field=models.ForeignKey(
                help_text="Which Step to use as a script for the Nudge",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nudges",
                to="mindframe.step",
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="branch_reason",
            field=models.CharField(
                choices=[
                    ("main", "Not a branch - part of the main trunk of the conversation"),
                    ("expert", "Expert completion/imagined alternative"),
                    ("play", "Simulation/reset to create alternative line of conversation"),
                    ("undo", "Undo in role-play"),
                ],
                default="main",
                max_length=25,
            ),
        ),
    ]
