# Generated by Django 5.1.6 on 2025-03-14 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0032_conversation_synthetic_therapist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="synthetic_client",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="synthetic_therapist",
        ),
        migrations.RemoveField(
            model_name="intervention",
            name="default_speaker",
        ),
        migrations.AddField(
            model_name="customuser",
            name="intervention",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a Bot user, which Intervention does it use?",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mindframe.intervention",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="default_bot_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The default Bot to use as a speaker for this intervention (e.g. if used in a synthetic conversation)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_interventions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="turn",
            name="turn_type",
            field=models.CharField(
                choices=[("utterance", "Utterance"), ("join", "Join")], default="utterance"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("system_developer", "System Developer"),
                    ("intervention_developer", "Intervention Developer"),
                    ("client", "Client"),
                    ("supervisor", "Supervisor"),
                    ("therapist", "Therapist"),
                    ("bot", "Bot"),
                ],
                default="client",
                max_length=30,
            ),
        ),
    ]
