# Generated by Django 5.1.3 on 2024-11-13 08:39

import django.db.models.deletion
import django.utils.timezone
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0032_alter_cycle_client_alter_cycle_intervention_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyntheticConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_one",
                        to="mindframe.treatmentsession",
                    ),
                ),
                (
                    "session_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_two",
                        to="mindframe.treatmentsession",
                    ),
                ),
            ],
        ),
    ]
