# Generated by Django 5.1.3 on 2024-11-13 08:39

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0033_alter_note_uuid_alter_treatmentsession_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="uuid",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="uuid",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="uuid",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True
            ),
        ),
    ]
