# Generated by Django 5.1.6 on 2025-03-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0034_remove_turn_text_source_alter_turn_turn_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="telegram_conversation_id",
            new_name="chat_room_id",
        ),
    ]
