# Generated by Django 5.1.3 on 2024-11-18 09:37

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0036_alter_intervention_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="sem_ver",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="intervention",
            unique_together={("title", "version", "sem_ver")},
        ),
    ]
