# Generated by Django 5.1.6 on 2025-03-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0036_turn_checkpoint_turn_checkpoint_resolved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interruption",
            name="debounce_turns",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Prevents the interruption from triggering again within this many turns.",
            ),
        ),
        migrations.AlterField(
            model_name="interruption",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interruptions",
                to="mindframe.intervention",
            ),
        ),
    ]
