# Generated by Django 5.1.6 on 2025-03-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0037_interruption_debounce_turns_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interruption",
            name="judgement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interruptions",
                to="mindframe.judgement",
            ),
        ),
    ]
