# Generated by Django 5.1.3 on 2024-11-18 09:37

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0037_alter_intervention_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervention",
            name="informaton",
        ),
        migrations.AlterField(
            model_name="note",
            name="uuid",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="uuid",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="uuid",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True
            ),
        ),
    ]
