# Generated by Django 5.1.3 on 2024-11-18 12:37

import autoslug.fields
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0039_remove_intervention_response_format_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgement",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="aa", editable=False, populate_from="title"
            ),
            preserve_default=False,
        ),
    ]
