# Generated by Django 5.1.6 on 2025-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0039_turn_resuming_from_alter_interruption_intervention_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interruption",
            name="slug",
            field=models.SlugField(default="inter", unique=True),
            preserve_default=False,
        ),
    ]
