# Generated by Django 5.1.6 on 2025-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0040_interruption_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interruption",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name="interruption",
            unique_together={("intervention", "slug")},
        ),
    ]
