# Generated by Django 5.1.3 on 2024-11-20 14:43

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0042_alter_note_uuid_alter_treatmentsession_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(choices=[("AZURE", "Azure"), ("OLLAMA", "Ollama")]),
                ),
                ("model_name", models.CharField(max_length=255)),
            ],
        ),
    ]
