# Generated by Django 5.1.6 on 2025-03-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0043_judgement_judgement_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="judgement",
            old_name="judgement_model",
            new_name="model",
        ),
    ]
