# Generated by Django 5.1.6 on 2025-03-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0044_rename_judgement_model_judgement_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interruption",
            options={"ordering": ["priority", "slug"]},
        ),
        migrations.AlterField(
            model_name="interruption",
            name="debounce_turns",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Prevents the interruption from triggering again within this many turns. Think carefully about this value. Consider what information is provided to the judgement which triggers the interruption. If the interruption is triggered by a judgement which includes the whole conversation history, you may need to increase this value to avoid repeatedly triggering the same interruption. For example, if the interruption is triggered by a judgement which assesses risk in the last 10 utterances, and directs the user to a risk assessment sequence, you may want to set this to 10 or more.",
            ),
        ),
        migrations.AlterField(
            model_name="interruption",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="The priority of the interruption. Interruptions with a _lower_ priority number will be evaluated earlier. If priorities are tied, the order of the interruptions is determined by the slug field (alphabetical order)",
            ),
        ),
        migrations.AlterField(
            model_name="judgement",
            name="model",
            field=models.ForeignKey(
                blank=True,
                help_text="If provided, this LLM will be used to evaluate this Judgement. If not provided, the intervention's default judgement model will be used.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_for_judgements",
                to="mindframe.llm",
            ),
        ),
    ]
