# Generated by Django 5.1.3 on 2024-11-20 17:10

import autoslug.fields
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0044_intervention_default_conversation_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="nickname",
            field=autoslug.fields.AutoSlugField(
                default="",
                editable=False,
                populate_from=["provider_name", "model_name"],
                unique=False,
            ),
            preserve_default=False,
        ),
    ]
