# Generated by Django 5.1.3 on 2024-11-20 17:13

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0045_llm_nickname_alter_note_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llm",
            name="nickname",
            field=models.SlugField(),
        ),
    ]
