# Generated by Django 5.1.6 on 2025-03-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0045_alter_interruption_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="chat_room_id",
            new_name="chat_id",
        ),
    ]
