# Generated by Django 5.2 on 2025-05-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0047_rename_chat_id_conversation_chat_room_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-turns__timestamp"]},
        ),
        migrations.RemoveField(
            model_name="turn",
            name="nudge",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("system_developer", "System Developer"),
                    ("intervention_developer", "Intervention Developer"),
                    ("client", "Client"),
                    ("supervisor", "Supervisor"),
                    ("bot", "Bot"),
                ],
                default="client",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="schedulednudge",
            name="completed_turn",
            field=models.ForeignKey(
                blank=True,
                help_text="The Turn created by this Nudge",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_nudges",
                to="mindframe.turn",
            ),
        ),
        migrations.AlterField(
            model_name="schedulednudge",
            name="turn",
            field=models.ForeignKey(
                help_text="Nudges scheduled following this turn",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nudges",
                to="mindframe.turn",
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="turn_type",
            field=models.CharField(
                choices=[
                    ("human", "Human utterance"),
                    ("bot", "Bot utterance"),
                    ("opening", "Fixed opening line"),
                    ("join", "Join"),
                ],
                max_length=255,
            ),
        ),
    ]
