# Generated by Django 5.1.3 on 2024-11-20 22:21

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0047_alter_note_uuid_alter_treatmentsession_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmlog",
            name="error",
        ),
        migrations.RemoveField(
            model_name="llmlog",
            name="session_state",
        ),
        migrations.AddField(
            model_name="llmlog",
            name="judgement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mindframe.judgement",
            ),
        ),
        migrations.AddField(
            model_name="llmlog",
            name="log_type",
            field=models.CharField(
                choices=[("ERROR", "Error"), ("USAGE", "Usage")], default="USAGE", max_length=25
            ),
        ),
        migrations.AddField(
            model_name="llmlog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mindframe.treatmentsession",
            ),
        ),
        migrations.AddField(
            model_name="llmlog",
            name="step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mindframe.step",
            ),
        ),
    ]
