# Generated by Django 5.2 on 2025-05-20 08:56

import django.db.models.deletion
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0048_alter_conversation_options_remove_turn_nudge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "webhook_validation_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bot_secret_token", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("telegram", "Telegram")], default="telegram", max_length=255
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="mindframe.intervention",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
