# Generated by Django 5.1.3 on 2024-11-21 07:59

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0049_remove_llmlog_traceback_llmlog_model_alter_note_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmlog",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
