# Generated by Django 5.2 on 2025-05-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0050_botinterface_bot_identifier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="botinterface",
            old_name="bot_identifier",
            new_name="bot_name",
        ),
    ]
