# Generated by Django 5.2 on 2025-05-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0052_remove_intervention_is_default_intervention"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="bot_interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mindframe.botinterface",
            ),
        ),
    ]
