# Generated by Django 5.1.3 on 2024-11-21 18:13

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0052_llmlog_turn_alter_note_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="session_state",
        ),
        migrations.AddField(
            model_name="note",
            name="turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="mindframe.turn",
            ),
        ),
        migrations.AlterField(
            model_name="llmlog",
            name="turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_calls",
                to="mindframe.turn",
            ),
        ),
    ]
