# Generated by Django 5.1.3 on 2024-11-22 09:26

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0053_remove_note_session_state_note_turn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepjudgement",
            name="use_as_feedback",
            field=models.BooleanField(
                default=False,
                help_text="Allow this judgement to be used as feedback when generating responses to the client. Exposed as a list of {{feedback}} in the prompt template.",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="uuid",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="uuid",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="uuid",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True
            ),
        ),
    ]
