# Generated by Django 5.2 on 2025-05-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0053_conversation_bot_interface"),
    ]

    operations = [
        migrations.AddField(
            model_name="botinterface",
            name="dev_mode",
            field=models.BooleanField(default=False),
        ),
    ]
