# Generated by Django 5.2 on 2025-05-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0054_botinterface_dev_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="botinterface",
            name="provider_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
