# Generated by Django 5.1.3 on 2024-11-22 09:28

import mindframe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0054_stepjudgement_use_as_feedback_alter_note_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="uuid",
            field=models.CharField(default=mindframe.models.s_uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="treatmentsession",
            name="uuid",
            field=models.CharField(default=mindframe.models.s_uuid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="turn",
            name="uuid",
            field=models.CharField(default=mindframe.models.s_uuid, editable=False, unique=True),
        ),
    ]
