# Generated by Django 5.2 on 2025-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0055_botinterface_provider_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="botinterface",
            name="provider_info_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
