# Generated by Django 5.2 on 2025-05-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0056_botinterface_provider_info_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intervention",
            options={"ordering": ["slug"]},
        ),
    ]
