# Generated by Django 5.1.3 on 2024-11-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0056_remove_stepjudgement_use_as_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmlog",
            name="prompt_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
