# Generated by Django 5.1.3 on 2024-11-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0057_llmlog_prompt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgement",
            name="task_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
