# Generated by Django 5.2 on 2025-05-21 17:19

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_lifecycle.mixins
import mindframe.shortuuidfield
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("mindframe", "0057_alter_intervention_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={},
        ),
        migrations.AlterField(
            model_name="note",
            name="judgement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="mindframe.judgement",
            ),
        ),
        migrations.CreateModel(
            name="ReferalToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start", models.DateTimeField(blank=True, null=True, verbose_name="start")),
                ("end", models.DateTimeField(blank=True, null=True, verbose_name="end")),
                ("is_removed", models.BooleanField(default=False)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "token",
                    mindframe.shortuuidfield.MFShortUUIDField(
                        blank=True, editable=False, max_length=27, unique=True
                    ),
                ),
                (
                    "permitted_interventions",
                    models.ManyToManyField(blank=True, to="mindframe.intervention"),
                ),
                ("valid_for_groups", models.ManyToManyField(blank=True, to="auth.group")),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ("timeframed", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Referal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "uuid",
                    mindframe.shortuuidfield.MFShortUUIDField(
                        blank=True, editable=False, max_length=27, unique=True
                    ),
                ),
                ("log", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referals",
                        to="mindframe.conversation",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mindframe.note",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referals",
                        to="mindframe.referaltoken",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
