# Generated by Django 5.2 on 2025-05-21 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0058_alter_conversation_options_alter_note_judgement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referal",
            name="note",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referal",
                to="mindframe.note",
            ),
        ),
    ]
