# Generated by Django 5.1.3 on 2024-11-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0058_judgement_task_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgement",
            name="task_summary",
            field=models.TextField(
                blank=True,
                help_text="A brief summary of the task or question asked by this judgement. E.g. 'Evaluate the client's emotional state'.",
                null=True,
            ),
        ),
    ]
