# Generated by Django 5.2 on 2025-05-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0059_alter_referal_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Whether this intervention is publicly visible on the web frontend.",
            ),
        ),
    ]
