# Generated by Django 5.1.3 on 2024-11-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0059_alter_judgement_task_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgement",
            name="pydantic_model_name",
        ),
        migrations.RemoveField(
            model_name="judgement",
            name="valid_options",
        ),
    ]
