# Generated by Django 5.1.3 on 2024-11-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0060_remove_judgement_pydantic_model_name_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="example",
            name="example_embedding_index",
        ),
        migrations.AlterUniqueTogether(
            name="example",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="transition",
            unique_together={("from_step", "to_step", "conditions")},
        ),
        migrations.RemoveField(
            model_name="example",
            name="embedding",
        ),
    ]
