# Generated by Django 5.2 on 2025-05-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0060_intervention_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A description of the intervention, for use in the web frontend.",
                null=True,
            ),
        ),
    ]
