# Generated by Django 5.2 on 2025-05-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0061_intervention_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="botinterface",
            name="budget_max_conversation_turns",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Maximum number of turns in a conversation", null=True
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="max_turns",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="turn",
            name="turn_type",
            field=models.CharField(
                choices=[
                    ("human", "Human utterance"),
                    ("bot", "Bot utterance"),
                    ("opening", "Fixed opening line"),
                    ("join", "Join"),
                    ("system", "System message"),
                ],
                max_length=255,
            ),
        ),
    ]
