# Generated by Django 5.2 on 2025-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0062_botinterface_budget_max_conversation_turns_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="default_max_turns",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
