# Generated by Django 5.1.5 on 2025-01-28 08:26

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0062_remove_llm_nickname_remove_llm_provider_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Litellm API key, defaults to LITELLM_API_KEY",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="base_url",
            field=models.CharField(
                blank=True,
                help_text="Litellm base URL defaults to LITELLM_ENDPOINT",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="llm",
            name="model_name",
            field=models.CharField(
                help_text="Litellm model name, e.g. llama3.2 or gpt-4o", max_length=255
            ),
        ),
    ]
