# Generated by Django 5.2 on 2025-05-28 11:47

import django.db.models.deletion
from django.db import migrations, models


def null_missing_model_ids(apps, schema_editor):
    Tool = apps.get_model("llmtools", "Tool")
    Judgement = apps.get_model("mindframe", "Judgement")
    Intervention = apps.get_model("mindframe", "Intervention")

    LLM = apps.get_model("llmtools", "LLM")
    existing_ids = set(LLM.objects.values_list("id", flat=True))
    Tool.objects.exclude(model_id__in=existing_ids).update(model_id=None)

    Intervention.objects.all().update(default_judgement_model=None)
    Intervention.objects.all().update(default_chunking_model=None)
    Intervention.objects.all().update(default_conversation_model=None)

    Judgement.objects.all().update(model=None)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0014_alter_tool_model"),
        ("mindframe", "0063_intervention_default_max_turns"),
    ]

    operations = [
        migrations.RunPython(null_missing_model_ids, reverse_code=noop),
    ]
