# Generated by Django 5.1.5 on 2025-01-28 13:47

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0063_llm_api_key_llm_base_url_alter_llm_model_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="default_chunking_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for_chunking",
                to="mindframe.llm",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="example",
            unique_together={("intervention", "title")},
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mindframe.intervention"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mindframe.treatmentsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoryChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chunk_start", models.IntegerField()),
                ("chunk_end", models.IntegerField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1024)),
                (
                    "memory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="mindframe.memory",
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="embedding_index",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
