# Generated by Django 5.1.5 on 2025-01-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0064_intervention_default_chunking_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorychunk",
            name="embedded_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
