# Generated by Django 5.2 on 2025-05-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0014_alter_tool_model"),
        ("mindframe", "0064_alter_intervention_default_conversation_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgement",
            name="model",
            field=models.ForeignKey(
                blank=True,
                help_text="If provided, this LLM will be used to evaluate this Judgement. If not provided, the intervention's default judgement model will be used.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_for_judgements",
                to="llmtools.llm",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="default_conversation_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for_conversations",
                to="llmtools.llm",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="default_chunking_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for_chunking",
                to="llmtools.llm",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="default_judgement_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for_judgements",
                to="llmtools.llm",
            ),
        ),
        migrations.DeleteModel(
            name="LLM",
        ),
    ]
