# Generated by Django 5.1.5 on 2025-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0065_memorychunk_embedded_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memorychunk",
            old_name="chunk_end",
            new_name="end",
        ),
        migrations.RenameField(
            model_name="memorychunk",
            old_name="chunk_start",
            new_name="start",
        ),
        migrations.AlterField(
            model_name="memorychunk",
            name="embedded_text",
            field=models.TextField(
                blank=True,
                help_text="The actual text embedded (may include extra tokens to contextualise/summarise passage to aid matching)",
                null=True,
            ),
        ),
    ]
