# Generated by Django 5.2 on 2025-05-28 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0017_tool_credentials_alter_tool_model"),
        ("mindframe", "0065_alter_judgement_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="llm_credentials",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="llmtools.llmcredentials"
            ),
        ),
    ]
