# Generated by Django 5.2 on 2025-05-28 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0066_conversation_llm_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="default_chunking_model",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for_chunking",
                to="llmtools.llm",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="intervention",
            name="default_conversation_model",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for_conversations",
                to="llmtools.llm",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="intervention",
            name="default_judgement_model",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for_judgements",
                to="llmtools.llm",
            ),
            preserve_default=False,
        ),
    ]
