# Generated by Django 5.1.5 on 2025-01-28 13:58

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0066_rename_chunk_end_memorychunk_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorychunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AlterField(
            model_name="memorychunk",
            name="end",
            field=models.IntegerField(help_text="The end position of the chunk in the memory"),
        ),
        migrations.AlterField(
            model_name="memorychunk",
            name="start",
            field=models.IntegerField(
                help_text="The start position of the chunk in the memory (chars)"
            ),
        ),
    ]
