# Generated by Django 5.2 on 2025-05-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0017_tool_credentials_alter_tool_model"),
        ("mindframe", "0067_alter_intervention_default_chunking_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botinterface",
            name="llm_credentials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="llmtools.llmcredentials",
            ),
        ),
    ]
