# Generated by Django 5.1.5 on 2025-01-30 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0067_alter_memorychunk_embedding_alter_memorychunk_end_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memory",
            options={"verbose_name_plural": "Memories"},
        ),
        migrations.AlterField(
            model_name="memory",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to="mindframe.intervention",
            ),
        ),
    ]
