# Generated by Django 5.2 on 2025-05-30

import django.db.models.deletion
from django.db import migrations, models


def set_llm_credentials(apps, schema_editor):
    LLMCredentials = apps.get_model("llmtools", "LLMCredentials")
    ReferalToken = apps.get_model("mindframe", "ReferalToken")

    db_alias = schema_editor.connection.alias
    default_cred = LLMCredentials._default_manager.using(db_alias).first()
    if not default_cred:
        raise RuntimeError("No LLMCredentials object found to use as default.")

    ReferalToken._default_manager.using(db_alias).filter(llm_credentials__isnull=True).update(
        llm_credentials=default_cred
    )


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0018_alter_llmcredentials_llm_api_key_and_more"),
        ("mindframe", "0068_botinterface_llm_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="referaltoken",
            name="llm_credentials",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="llmtools.llmcredentials",
            ),
        ),
        migrations.AlterField(
            model_name="botinterface",
            name="llm_credentials",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank to use the default credentials.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="llmtools.llmcredentials",
            ),
        ),
        migrations.RunPython(set_llm_credentials, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="referaltoken",
            name="llm_credentials",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="llmtools.llmcredentials",
            ),
        ),
    ]
