# Generated by Django 5.1.5 on 2025-01-31 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0068_alter_memory_options_alter_memory_intervention"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Example",
        ),
    ]
