# Generated by Django 5.2 on 2025-06-01 08:39

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields
from django.db import migrations, models

import mindframe.shortuuidfield


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0018_alter_llmcredentials_llm_api_key_and_more"),
        ("mindframe", "0069_referaltoken_llm_credentials_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referaltoken",
            name="llm_credentials",
        ),
        migrations.RemoveField(
            model_name="referaltoken",
            name="permitted_interventions",
        ),
        migrations.RemoveField(
            model_name="referaltoken",
            name="valid_for_groups",
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-turns__timestamp"]},
        ),
        migrations.RemoveField(
            model_name="botinterface",
            name="budget_max_conversation_turns",
        ),
        migrations.RemoveField(
            model_name="botinterface",
            name="llm_credentials",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="llm_credentials",
        ),
        migrations.CreateModel(
            name="UsagePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start", models.DateTimeField(blank=True, null=True, verbose_name="start")),
                ("end", models.DateTimeField(blank=True, null=True, verbose_name="end")),
                ("is_removed", models.BooleanField(default=False)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "referal_token",
                    mindframe.shortuuidfield.MFShortUUIDField(
                        blank=True, editable=False, max_length=27, unique=True
                    ),
                ),
                (
                    "max_conversation_turns",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Maximum number of turns in a conversation", null=True
                    ),
                ),
                (
                    "llm_credentials",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to use the default credentials.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="llmtools.llmcredentials",
                    ),
                ),
                (
                    "permitted_interventions",
                    models.ManyToManyField(blank=True, to="mindframe.intervention"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ("timeframed", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="UserReferal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "uuid",
                    mindframe.shortuuidfield.MFShortUUIDField(
                        blank=True, editable=False, max_length=27, unique=True
                    ),
                ),
                ("log", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "note",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_referal",
                        to="mindframe.note",
                    ),
                ),
                (
                    "usage_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referals",
                        to="mindframe.usageplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user_referal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mindframe.userreferal",
            ),
        ),
        migrations.DeleteModel(
            name="Referal",
        ),
        migrations.DeleteModel(
            name="ReferalToken",
        ),
    ]
