# Generated by Django 5.1.5 on 2025-02-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0069_delete_example"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={"ordering": ["intervention", "order", "title"]},
        ),
        migrations.AddField(
            model_name="step",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
