# Generated by Django 5.2 on 2025-06-01 09:15

import django.db.models.deletion
import shortuuid
from django.db import migrations, models


def create_default_usage_plan_and_backfill_referrals(apps, schema_editor):
    UsagePlan = apps.get_model("mindframe", "UsagePlan")
    LLMCredentials = apps.get_model("llmtools", "LLMCredentials")
    Conversation = apps.get_model("mindframe", "Conversation")
    UserReferal = apps.get_model("mindframe", "UserReferal")

    # Get or create default credentials (assumes one exists)
    default_creds = LLMCredentials._default_manager.get(pk=1)
    if not default_creds:
        raise RuntimeError("No default LLMCredentials found.")

    # Create default UsagePlan if it doesn't exist
    plan, _ = UsagePlan._default_manager.get_or_create(
        label="Default UsagePlan",
        defaults={
            "referal_token": shortuuid.uuid(),
            "llm_credentials": default_creds,
            "max_conversation_turns": 100,
        },
    )

    # Loop over Conversations without user_referal
    for convo in Conversation._default_manager.filter(user_referal__isnull=True):
        referral = UserReferal._default_manager.create(
            uuid=shortuuid.uuid(),
            usage_plan=plan,
        )
        convo.user_referal = referral
        convo.save(update_fields=["user_referal"])


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0070_remove_referaltoken_llm_credentials_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_usage_plan_and_backfill_referrals),
    ]
