# Generated by Django 5.1.5 on 2025-02-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0070_alter_step_options_step_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmlog",
            name="variable_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
