# Generated by Django 5.1.5 on 2025-02-04 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0071_llmlog_variable_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="turn",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="syntheticconversation",
            name="last_speaker_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mindframe.turn",
            ),
        ),
    ]
