# Generated by Django 5.2 on 2025-06-01 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0072_alter_conversation_user_referal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="user_referal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="mindframe.userreferal"
            ),
        ),
    ]
