# Generated by Django 5.1.5 on 2025-02-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0072_alter_turn_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syntheticconversation",
            name="additional_turns_scheduled",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of additional turns scheduled for this conversation (should be completed by a worker task — don't edit directly)",
            ),
        ),
    ]
