# Generated by Django 5.2 on 2025-06-01 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0073_alter_conversation_user_referal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={},
        ),
        migrations.AddField(
            model_name="botinterface",
            name="default_usage_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bot_interfaces",
                to="mindframe.usageplan",
            ),
        ),
    ]
