# Generated by Django 5.1.5 on 2025-02-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0073_syntheticconversation_additional_turns_scheduled"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="source_type",
            field=models.CharField(
                choices=[("human", "Human"), ("AI", "AI")], default="human", max_length=25
            ),
        ),
    ]
