# Generated by Django 5.1.5 on 2025-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0073_syntheticconversation_additional_turns_scheduled"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("system_developer", "System Developer"),
                    ("intervention_developer", "Intervention Developer"),
                    ("client", "Client"),
                    ("supervisor", "Supervisor"),
                    ("therapist", "Therapist"),
                ],
                default="AI generated text",
                max_length=30,
            ),
        ),
    ]
