# Generated by Django 5.2 on 2025-06-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0075_auto_20250601_1214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botinterface",
            name="default_usage_plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bot_interfaces",
                to="mindframe.usageplan",
            ),
            preserve_default=False,
        ),
    ]
