# Generated by Django 5.2 on 2025-06-01 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0076_alter_botinterface_default_usage_plan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-pk"]},
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user_referal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="mindframe.userreferal",
            ),
        ),
    ]
