# Generated by Django 5.2 on 2025-06-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0077_alter_conversation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreferal",
            name="redeemed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
