# Generated by Django 5.2 on 2025-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindframe", "0078_userreferal_redeemed"),
    ]

    operations = [
        migrations.AddField(
            model_name="botinterface",
            name="other_interventions_allowed",
            field=models.ManyToManyField(blank=True, to="mindframe.intervention"),
        ),
    ]
