services:
  base:
    container_name: mindframe-base
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        MINDFRAME_COMMIT: main
        BUILDKIT_PROGRESS: plain
    image: "${BASE_IMAGE_NAME:-mindframe:production}"
    networks:
      - backend

  web:
    container_name: "${CONTAINER_NAME_PREFIX:-}web"
    restart: unless-stopped
    labels:
      caddy: "web.mindframe.llemma.net"
      caddy.reverse_proxy: "{{upstreams 8000}}"
    ports:
      - "${WEB_PORT:-8080}:8000"
    networks:
      - caddy
      - backend
    image: "${BASE_IMAGE_NAME:-mindframe:production}"
    command:
      [
        "sh",
        "-c",
        "uvicorn config.asgi:application --workers 1 --host 0.0.0.0 --port 8000 --log-level debug"
      ]

  chat:
    container_name: "${CONTAINER_NAME_PREFIX:-}chat"
    restart: unless-stopped
    labels:
      caddy: "bot.mindframe.llemma.net"
      caddy.reverse_proxy: "{{upstreams 8000}}"
    ports:
      - "${CHAT_PORT:-8081}:8000"
    networks:
      - caddy
      - backend
    image: "${BASE_IMAGE_NAME:-mindframe:production}"
    command:
      [
        "sh",
        "-c",
        "python chatbot.py"
      ]

  worker:
    user: "1000:1000" # celery can't run as root
    container_name: "${CONTAINER_NAME_PREFIX:-mindframe}-worker"
    restart: unless-stopped
    image: "${BASE_IMAGE_NAME:-mindframe:production}"
    networks:
      - backend
    command:
      [
        "sh",
        "-c",
        "celery --app mindframe worker --pool=solo --loglevel=debug"
      ]
