volumes:
  postgres_data: {}

services:
  redis:
    image: redis:alpine
    ports: ["6379:6379"]

  postgres:
    image: pgvector/pgvector:pg17
    ports: ["5432:5432"]
    env_file: [secrets.env]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-database.sh:/usr/bin/create-database.sh
