services:
  postgres:
    env_file:
      - ~/.secrets/test.mindframe.llemma.net.env
  web:
    env_file:
      - ~/.secrets/test.mindframe.llemma.net.env
  chat:
    env_file:
      - ~/.secrets/test.mindframe.llemma.net.env
  worker:
    env_file:
      - ~/.secrets/test.mindframe.llemma.net.env
