# Generated by Django 5.1.5 on 2025-02-10 00:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mindframe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "prompt",
                    models.TextField(
                        help_text="Use curly braces for placeholders, e.g.: 'Hello {user_name}, how are you?'"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mindframe.llm"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tool_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_keys",
                        to="llmtools.tool",
                    ),
                ),
            ],
        ),
    ]
