# Generated by Django 5.1.5 on 2025-01-30 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mindframe", "0068_alter_memory_options_alter_memory_intervention"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "prompt",
                    models.TextField(
                        help_text="Use curly braces for placeholders, e.g.: 'Hello {user_name}, how are you?'"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mindframe.llm"
                    ),
                ),
            ],
        ),
    ]
