# Generated by Django 5.1.5 on 2025-02-06 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "prompt",
                    models.TextField(
                        help_text="Use curly braces for placeholders, e.g.: 'Hello {user_name}, how are you?'"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tool_key", models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
