# Generated by Django 5.1.5 on 2025-02-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("llmtools", "0001_initial"),
        ("mindframe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mindframe.llm"
            ),
        ),
        migrations.AddField(
            model_name="toolkey",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_keys",
                to="llmtools.tool",
            ),
        ),
    ]
