# Generated by Django 5.2 on 2025-05-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("complete", models.BooleanField(default=False)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="llmtools.tool"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.TextField()),
                ("source_file", models.FileField(upload_to="source_files")),
                ("completed", models.DateTimeField(null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="llmtools.jobgroup"
                    ),
                ),
            ],
        ),
    ]
