# Generated by Django 5.2 on 2025-05-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0002_jobgroup_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="prompt",
            field=models.TextField(
                help_text="Use ${curly} braces for source placeholder, e.g.: 'User input document text: ${user_name}. Extract the title: [[extract:title]]'"
            ),
        ),
    ]
