# Generated by Django 5.2 on 2025-05-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0002_jobgroup_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="llmtools.jobgroup",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="source_file",
            field=models.FileField(max_length=4096, upload_to="source_files"),
        ),
    ]
