# Generated by Django 5.2 on 2025-05-19 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0003_alter_tool_prompt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobgroup",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_groups",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
