# Generated by Django 5.2 on 2025-05-19 11:09

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0004_jobgroup_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="jobgroup",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="job",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="jobgroup",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobgroup",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
