# Generated by Django 5.2 on 2025-05-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0005_alter_job_options_alter_jobgroup_options_job_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="source",
        ),
        migrations.AddField(
            model_name="job",
            name="context",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="tool",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="llmtools.tool"
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="include_source",
            field=models.BooleanField(default=False),
        ),
    ]
