# Generated by Django 5.2 on 2025-05-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0006_remove_job_source_job_context_job_tool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="llmtools.jobgroup",
            ),
        ),
    ]
