# Generated by Django 5.2 on 2025-05-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0007_alter_job_group"),
        ("mindframe", "0048_alter_conversation_options_remove_turn_nudge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tool",
            name="include_source",
            field=models.BooleanField(
                default=False,
                help_text="Include the source text in the results JSON (can be quite large).",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="model",
            field=models.ForeignKey(
                help_text="The LLM to use for this Tool",
                on_delete=django.db.models.deletion.CASCADE,
                to="mindframe.llm",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="prompt",
            field=models.TextField(
                default="{{source}}\n\nQuestion about the source\n\n[[response]]",
                help_text="Use {{curly}} braces for the source placeholder, and square brackets for LLM completions, e.g. [[response]]",
            ),
        ),
    ]
