# Generated by Django 5.2 on 2025-05-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0008_job_cancelled_alter_tool_include_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobgroup",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
