# Generated by Django 5.2 on 2025-05-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0009_jobgroup_cancelled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobgroup",
            options={"ordering": ["-created"]},
        ),
    ]
