# Generated by Django 5.2 on 2025-05-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0010_alter_jobgroup_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobgroup",
            name="complete",
        ),
    ]
