# Generated by Django 5.2 on 2025-05-21 08:24

from django.db import migrations, models
import uuid


def assign_uuids(apps, schema_editor):
    JobGroup = apps.get_model("llmtools", "JobGroup")
    for obj in JobGroup.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0010_alter_jobgroup_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobgroup",
            name="complete",
        ),
        # Step 1: Add field as nullable to allow populating existing records
        migrations.AddField(
            model_name="jobgroup",
            name="uuid",
            field=models.UUIDField(null=True, unique=True),
        ),
        # Step 2: Populate existing rows
        migrations.RunPython(assign_uuids, reverse_code=migrations.RunPython.noop),
        # Step 3: Enforce non-null and default after population
        migrations.AlterField(
            model_name="jobgroup",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
