# Generated by Django 5.2 on 2025-05-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0011_remove_jobgroup_complete"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "llm_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Override for LLM API key, used for this BotInterface.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "llm_base_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional base URL for Litellm/OpenAI proxy for this interface.",
                        max_length=1024,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Litellm model name, e.g. llama3.2 or gpt-4o", max_length=255
                    ),
                ),
                (
                    "credentials",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llmtools.llmcredentials",
                    ),
                ),
            ],
            options={
                "unique_together": {("model_name",)},
            },
        ),
    ]
