# Generated by Django 5.2 on 2025-05-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0012_llmcredentials_llm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="model",
            field=models.ForeignKey(
                help_text="The LLM to use for this Tool",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mindframe.llm",
            ),
        ),
    ]
