# Generated by Django 5.2 on 2025-05-28 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0013_alter_tool_model"),
    ]

    operations = []
