# Generated by Django 5.2 on 2025-05-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0014_alter_tool_model"),
        ("mindframe", "0064_alter_intervention_default_conversation_model_and_more"),
    ]

    operations = []
