# Generated by Django 5.2 on 2025-05-28 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0016_auto_20250528_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="credentials",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="llmtools.llmcredentials"
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="model",
            field=models.ForeignKey(
                default=1,
                help_text="The LLM to use for this Tool",
                on_delete=django.db.models.deletion.CASCADE,
                to="llmtools.llm",
            ),
        ),
    ]
