# Generated by Django 5.2 on 2025-05-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0017_tool_credentials_alter_tool_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmcredentials",
            name="llm_api_key",
            field=models.CharField(
                blank=True, help_text="Litellm API key.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="llmcredentials",
            name="llm_base_url",
            field=models.CharField(
                blank=True,
                help_text="Optional base URL for Litellm/OpenAI proxy.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
