# Generated by Django 5.2 on 2025-05-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0017_tool_credentials_alter_tool_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llm",
            name="credentials",
        ),
    ]
