# Generated by Django 5.2 on 2025-06-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llmtools", "0018_alter_llmcredentials_llm_api_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="llmcredentials",
            options={"verbose_name_plural": "LLM Credentials"},
        ),
    ]
