graph TD
    A[Welcome & Rapport] --> B[Intro Self]
    B --> C[Assess State]
    C --> D[Negotiate Agenda]
    D --> E[Build Discrepancy]
    E --> F[Build Self-Efficacy]
    F --> G[Explore Benefits]
    G --> H[Formulate Plan]
    H --> I[Check Confidence]
    I --> J[Strengthen Plan]
    I --> E
    J --> K[Elicit Barriers]
    K --> L[Overcome Barriers]
    L--> |mention additional barrier| L 
    L --> M[Check Plan]
    M --> J
    M --> N[Find Daily Cue]